version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gw_postgres_container
    environment:
      POSTGRES_DB: gateway_db
      POSTGRES_USER: gw_user_db
      POSTGRES_PASSWORD: test
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
